/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sumFactorials.h"


void
sum_prog_1(char *host,int x)
{
	CLIENT *clnt;
	long  *result_1;
	number  sumfactorial_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUM_PROG, SUM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	sumfactorial_1_arg.x=x;
	result_1 = sumfactorial_1(&sumfactorial_1_arg, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
	    printf("Result: %ld \n", *result_1);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host NUMBER \n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sum_prog_1 (host, atoi(argv[2]));

exit (0);
}
