/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sumFactorials.h"

long *
sumfactorial_1_svc(number *argp, struct svc_req *rqstp)
{
	static long  result;
    long total=0;
    
	printf("SERVER: sumFactorial(%d) was called \n",argp->x);
    for (int i=1; i<=argp->x; i++){
        printf("Calculating factorial for %d \n",i);
        long factorial=1;
        for (int j=1; j<=i; j++){
            factorial*=j;        
        }
        printf("Factorial for %d is %ld \n", i,factorial);
        total+=factorial;
    }
    result = total;


	return &result;
}
